### ISSUE TITLE
Crash when launch app

### ISSUE THREAD

**Issue by Sun020422** [akorb/SteamShutdown#43] opened 2021-08-03 15:01 UTC
2021/8/3 22:58:08: System.TypeInitializationException: “SteamShutdown.Steam”的类型初始值设定项引发异常。 ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 无法对 null 引用执行运行时绑定
   在 CallSite.Target(Closure , CallSite , Object )
   在 System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   在 SteamShutdown.Steam.GetLibraryPaths(String installationPath)
   在 SteamShutdown.Steam..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   在 SteamShutdown.CustomApplicationContext..ctor()
   在 SteamShutdown.SteamShutdown.Main()
2021/8/3 22:58:40: System.TypeInitializationException: “SteamShutdown.Steam”的类型初始值设定项引发异常。 ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 无法对 null 引用执行运行时绑定
   在 CallSite.Target(Closure , CallSite , Object )
   在 System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   在 SteamShutdown.Steam.GetLibraryPaths(String installationPath)
   在 SteamShutdown.Steam..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   在 SteamShutdown.CustomApplicationContext..ctor()
   在 SteamShutdown.SteamShutdown.Main()
2021/8/3 22:59:44: System.TypeInitializationException: “SteamShutdown.Steam”的类型初始值设定项引发异常。 ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 无法对 null 引用执行运行时绑定
   在 CallSite.Target(Closure , CallSite , Object )
   在 System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   在 SteamShutdown.Steam.GetLibraryPaths(String installationPath)
   在 SteamShutdown.Steam..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   在 SteamShutdown.CustomApplicationContext..ctor()
   在 SteamShutdown.SteamShutdown.Main()

**Comment by akorb** [comment] 2021-08-03 18:36
Duplicate of https://github.com/akorb/SteamShutdown/issues/42

Can you please check the version of this post and comment on it? https://github.com/akorb/SteamShutdown/issues/42#issuecomment-891318349

**Closed as completed by akorb** 2021-08-03 18:36 UTC
